version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: clo_clo_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "4q@6Xfz-5ZT3]q"
      POSTGRES_DB: clo_clo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Optionnel : pgAdmin pour visualiser la DB localement
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: clo_clo_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clo-clo.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
